### ISSUE TITLE
pix can't take off by using dronekit .

### ISSUE THREAD

**Issue by yudoutingle** [Drones4STEM/DroneController#1]
hi , handsome boy , i really need help .
i control my drone by using dronekit , i have a APM with AC3.2.1 and a PIX with AC3.3.3 .
the APM can take off well with the dronekit examples but the PIX didnt work well with that .
the pix cant take off , i change fireware version 3.2.1 3.3.3 and 3.5.5 ,but all of these version didnt work with real copter . this really confused me , ireally need help .thank u  in advance .

**Comment by rogerwwww** [comment]
Hi,
There are many reasons that will cause such kind of problem, like inappropriate bound rate, wrong flying mode etc. Since that you are using dronekit examples, you had better ask the same question at the [dronekit page](https://github.com/dronekit/dronekit-python/issues), and provide your log file and parameter configuration file if possible.

**Comment by yudoutingle** [comment]
hi , handsome boy , i am a student in southeast Univercity ,can i add u contact number ? my qq is 410119646  , thanks  in advance .
